package com.tennisdb.server.Model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Column;

@Entity
@Table(name="video")
public class Video {
	
	@Column(name="videoId")
	@Id
	@GeneratedValue
	private Integer videoId;

	@Column(name="url")
	private String url;

	// Default no args constructor
	public Video(){}

	/**
     * Whem posting a new Video, the id can be generated by the database. In that case, a constructor without
	 * videoId is needed
	 */
	public Video(String url) {
		this.url = url;
	}

	/**
     * Whem retrieving a Video from the database, all fields will be needed. In that case, a constructor with all
     * fields is needed.
	 */
	public Video(Integer id, String url) {
		this.videoId = id;
		this.url = url;
	}

	public Integer getVideoId() {
		return this.videoId;
	}

	public void setVideoId(Integer id) {
		this.videoId = id;
	}

	public String getVideoUrl() {
		return this.url;
	}

	public void setVideoUrl(String url) {
		this.url = url;
	}

	/**
     * Overriding the default toString() method allows for easy debugging.
     * @return a String representation of this class.
     */
	public String toString() {
		return "Video {" +
				"videoId=" + videoId +
				", url=" + url + 
				" }";
	}

}
