package com.tennisdb.server.Model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import jakarta.persistence.Column;

@Entity
@Table(name="video")
@AllArgsConstructor
@NoArgsConstructor
@Data
public class Video {
	
	@Column(name="videoId")
	@Id
	@GeneratedValue
	private Integer videoId;

	@Column(name="tournament")
	private String tournament;

	//year is a reserved keyword in H2 database. 
	// When Hibernate tries to create the table, H2 doesn't allow year as a column name without proper escaping.
	@Column(name="video_year") // Escape the year column name
	private Integer year;

	@Column(name="youtubeId")
	private String youtubeId;

	@Column(name="player1")
	private String player1;

	@Column(name="player2")
	private String player2;

	@Column(name="title")
	private String title;

	@Column(name="round")
	private String round;


	/**
     * Whem posting a new Video, the id can be generated by the database. In that case, a constructor without
	 * videoId is needed
	 */
	public Video(String tournament, Integer year, String url, String player1, String player2) {
		this.tournament = tournament;
		this.year = year;
		this.youtubeId = url;
		this.player1 = player1;
		this.player2 = player2;
	}

	/**
     * Overriding the default toString() method allows for easy debugging.
     * @return a String representation of this class.
     */
	@Override
	public String toString() {
		return "Video {" +
				"videoId=" + videoId +
				", youtubeId=" + youtubeId + 
				" }";
	}

}
